baseURL = "https://pranamshetty.dev"
languageCode = 'en-us'
title = 'Pranam Shetty'
theme = 'hugo-noir'

# URL handling
relativeURLs = true
canonifyURLs = true

# Multilingual configuration
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Pranam Shetty"
    weight = 1
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        pageRef = "/about"
        weight = 1
      [[languages.en.menu.main]]
        name = "Experience"
        pageRef = "/experience"
        weight = 2
      [[languages.en.menu.main]]
        name = "Projects"
        pageRef = "/projects"
        weight = 3
      [[languages.en.menu.main]]
        name = "Blogs"
        pageRef = "/blogs"
        weight = 4
      [[languages.en.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 5
  [languages.es]
    languageName = "Español"
    title = "Pranam Shetty"
    weight = 2
    contentDir = "content/es"
    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Sobre Mí"
        pageRef = "/about"
        weight = 1
      [[languages.es.menu.main]]
        name = "Experiencia"
        pageRef = "/experience"
        weight = 2
      [[languages.es.menu.main]]
        name = "Proyectos"
        pageRef = "/projects"
        weight = 3
      [[languages.es.menu.main]]
        name = "Blogs"
        pageRef = "/blogs"
        weight = 4
      [[languages.es.menu.main]]
        name = "Contacto"
        pageRef = "/contact"
        weight = 5
  [languages.fr]
    languageName = "Français"
    title = "Pranam Shetty"
    weight = 3
    contentDir = "content/fr"
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        name = "À Propos"
        pageRef = "/about"
        weight = 1
      [[languages.fr.menu.main]]
        name = "Expérience"
        pageRef = "/experience"
        weight = 2
      [[languages.fr.menu.main]]
        name = "Projets"
        pageRef = "/projects"
        weight = 3
      [[languages.fr.menu.main]]
        name = "Blogs"
        pageRef = "/blogs"
        weight = 4
      [[languages.fr.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 5

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
# Basic profile information - common across languages
name = "Pranam Shetty"
profile_image = "/images/profile.jpg"
discord = "prxshetty"
github = "https://github.com/prxshetty"
github_username = "prxshetty"
email = "prxshetty@gmail.com"
twitter = "https://www.twitter.com/prxshetty"
twitter_username = "prxshetty"
medium = "https://www.medium.com/@prxshetty"
linkedin = "https://www.linkedin.com/in/prxshetty"
linkedin_username = "prxshetty"
instagram = "https://instagram.com/prxshetty"
leetcode = "https://leetcode.com/rinzler26"
leetcode_username = "rinzler26"
monkeytype = "https://monkeytype.com/profile/prxshetty"
monkeytype_username = "prxshetty"
kaggle = "https://www.kaggle.com/prxshetty"
kaggle_username = "prxshetty"

[[params.honors]]
institution = "K K Wagh Arts Commerce Science and Computer Science College"
title = "Academic Topper"
date = "March 2023"

[[params.honors]]
institution = "Podar International School, Nashik"
title = "Academic Excellence Award"
date = "October 2017"

[[params.certifications]]
title = "AI Vector Search Professional"
company = "Oracle"
date = "Feb 2025"
url = "https://catalog-education.oracle.com/ords/certview/sharebadge?id=E5845422D7DE89C09337652BAF48826F0C6C9CB6FAA7B0FE9F8B1AF447FACAB9"

[[params.certifications]]
title = "Generative AI Professional"
company = "Oracle"
date = "July 2024"
url = "https://catalog-education.oracle.com/ords/certview/sharebadge?id=5C2C44615B73F678DF85E44418348C3535ABCE032C9F7E82F196472434C80BCB"

[[params.certifications]]
title = "AI Foundations Associate"
company = "Oracle"
date = "April 2025"
url = "https://catalog-education.oracle.com/ords/certview/sharebadge?id=FDAC04F9FD0E2793459AAC3EE02DE9131DA3B7B34C20A361CAEFC71059B86EA8"

[[params.voluntary]]
role = "Volunteer"
organization = "Bunts Sangha"
period = "2009 - Present"
description = "As a volunteer at Bunts Sangha Nashik, I tutored students, prepared study materials, organized festivals and traditional performances, visited elderly to promote community unity, and coordinated fundraising campaigns."

# Main menu (used as fallback if language-specific menu is not defined)
[menu]
  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 1
  [[menu.main]]
    name = "Experience"
    pageRef = "/experience"
    weight = 2
  [[menu.main]]
    name = "Projects"
    pageRef = "/projects"
    weight = 3
  [[menu.main]]
    name = "Blogs"
    pageRef = "/blogs"
    weight = 4
  [[menu.main]]
    name = "Contact Me"
    pageRef = "/contact"
    weight = 5

